### ISSUE TITLE
RemoteProperties are not optimized for large tables

### ISSUE THREAD

**Issue by CountMyBands** [Sleitnick/RbxUtil#135]
When dealing with sizable tables and remote properties, updating those tables can get quite costly network-wise. A personal example in my own game is leaderboards. I use remote properties for them because they are convenient for instantly retrieving the value when it's ready, and getting updates after that. When I set a new value on the server, which is a table of all the players on the leaderboard, the client receives all of this information, even information it already has.

I think this could be fixed in one of two ways:

1. If a new value and an old value are both tables, then send the difference between them to the client and update accordingly.  
2. Create a new type `RemoteTable` with this functionality.

**Comment by bubshayz** [comment]
This shouldn't be handled by the internal code, instead, you should make some sort of wrapper over this and handle it on your own. 

We use a custom remote property / remote-signal implementation (albeit, similar to the RbxUtil ones but with improved API) alongside [Matter](https://eryn.io/matter/). We replicate matter components to the client and have an advanced replication system where we check for the difference between the old and new component data and send the difference data only to the client (which then merges in the 'difference' to the data it has). Additionally, for some components, we only send in specific members of it to the client instead of the entire data as a whole - in this way the average client's network receive rate (specifically) is low enough to not cause issues regarding scalability.

With **1**, RemoteProperties or RemoteSignals compressing data by default would give the developer no flexibility in managing replicated data, which is really bad for scalability and projects.

With **2**, I think it's just bloat and overcomplicates the overall API unnecessarily. Instead, a custom wrapper would be the best fit.

**Comment by Sleitnick** [comment]
Yeah, this would require a lot of code, and then uncertainty whether this should affect deep structures or not. Better to create your own system of managing data that can watch for changes and replicate when needed.
